name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel libffi-dev libssl-dev libncurses5-dev libsqlite3-dev libjpeg-dev zlib1g-dev libpng-dev liblzma-dev
          pip install --upgrade pip
          pip install buildozer==1.5.0 Cython
          sudo apt install -y libgl1-mesa-dev

      - name: Cache .buildozer folder
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/*.apk
